apiVersion: v1
kind: Pod
metadata:
  name: node-shell
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: shell
    image: busybox
    command:
    - sleep
    - "3600"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: root
  volumes:
  - name: root
    hostPath:
      path: /
  nodeSelector:
    kubernetes.io/hostname: <node-name>
  restartPolicy: Never
