apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-sh-runner-1
  namespace: ghactions
spec:
  replicas: 1
  template:
    spec:
      repository: it/vulnpatch
      labels:
        - arc
        - kubernetes
      env: []
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
